baseURL = "https://todayilearned.jm3.net/"
languageCode = "en-us"
title = "Rocker Panel"
theme = "rocker-panel"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"

[params]
  copyright = "© ← copyleft <abbr title='John Manoogian'>jm3</abbr> &mdash; all rights reserved, all wrongs      reversed, no punches pulled"
	subtitle = "Simple Hugo [theme](https://github.com/jm3/rocker-panel)"
	# Number of posts to show in recent posts list.
	recentPostsCount = 10
	# Content types which are excluded from recent posts and archive page.
	excludedTypes = ["page"]
  primaryType = "posts"
	featherIconsCDN = true

[[menu.main]]
name = "Home"
url = "/"
pre = "box"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
pre = "box"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
pre = "box"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
pre = "box"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/jm3"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/nerdshitposting"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tag = "tags"
